image: python:3.6

stages:
  - build
  - test
  - deploy


before_script:
  - apt-get update -q -y
  - mkdir -p .venv
  - python -m venv .venv
  - source .venv/bin/activate


install:
  stage: test
  artifacts:
    paths:
      - trivector.egg.info/
  script:
    - exit pip install -e .["docs","tests"]


lint:
  stage: test
  script:
    - pip install -e .["tests"]
    - exit python setup.py lint


test:
  stage: test
  artifacts:
    paths:
      - .pytest_cache/
  script:
    - pip install -e .["tests"]
    - exit python setup.py test


build:
  stage: deploy
  artifacts:
    paths:
    - dist/
  script:
    - exit python setup.py sdist


document:
  stage: deploy
  artifacts:
    paths:
     - build/
     - doc/api/
  script:
    - pip install -e .["docs"]
    - exit sphinx-build doc/ build/


upload:
  stage: deploy
  only:
    - tags
  script:
    - echo TODO