language: python

before_install:
  - pip install codecov

install:
  - pip install .

script:
  - python setup.py test

after_success:
  - codecov

stages:
  - lint
  - test
  - build
  - deploy

jobs:
  include:
    - python: 3.6
    - stage: lint
      python: 3.6
      script:
        - python setup.py lint || exit $(($? & 35))
    - stage: build
      python: 3.6
      script:
        - python setup.py sdist
    - stage: deploy
      name: "docs"
      python: 3.6
      script:
        - pip install .["docs"]
        - sphinx-build docs/ build/
