language: python

python: 3.6

before_install:
  - pip install codecov

install:
  - pip install .

script:
  - python setup.py test

after_success:
  - codecov

stages:
  - lint
  - test
  - build
  - doc
  - test_deploy
  - deploy

jobs:
  include:
    - stage: lint
      python: 3.6
      script:
        - python setup.py lint || exit $(($? & 35))
    - stage: test
    - python: 3.5
    - python: 3.7
      dist: xenial
    - stage: build
      python: 3.6
      install:
        - pip install . wheel
      script:
        - python setup.py sdist bdist_wheel
    - stage: doc
      python: 3.6
      install:
        - pip install .["docs"]
      script:
        - sphinx-build docs/ build/
    - stage: test_deploy
      python: 3.6
      deploy:
        provider: pypi
        user: nklapste
        password:
          secure: UP8MNQxZTpJ/5rsRnpsMLpKuH5dWKypBoNDUvMjKxkCFkVyVmmmudqp0lcE6tNOetrEnDk5N6PIT2j2cTWapZ4gAp56U+m4wrwHBDTp/mUSnPJCtKIVG1qv+0vdUGHpvyHTY1CfP+2dyG6gCoQm9syKOGMD1A3KIgWXNVX9z/KOJwY6UzfzmfgRizjao0yAV2wqYywsJsU8ykS9bt465lD0W27m33SoaAkUnPy2jH56N1Nm7mG7IwB+Mok+6+kSwMnmtAPuABR5F8jGVnY0qhy416x2CXWpkmXpywWWGoAAiu8ala7DOq2z4W8rJNC+AmhygDj3/oGLr8bQckumHvWyWd8GE3IH2F3mi5iYrBGjy/9Puygt+iJqsX2yi5Bv0OxIUMRYLhx4mjS3xt91X+BnmhtORv5JYkcxOeSqy7bIYGgwNx4eYMr0xwZsQ3db6S62CUbrPnse97Sa7WHJL8Z5h1g8TLfPO+jo87zkhTJDwyCq7clkhbnWwJ/dT26I7WpUvpbp7vGOzo6Ee+QtxTHsRTo7st8ShY1URYVQKIL4yG7vfDyPFjPJZpX2PpfrkoWanzvYRIWQpZ0zwC8yCcxIPYgMZdSFhjpuCwdF5qb3H4MyVUb1TuCuzB3Mj1UpqPAa4Axp7b/fUtvEXaLFg3i9SSZQYhH4b6B4kIU8Y/Kw=
        server: https://test.pypi.org/legacy/
        distributions: "sdist bdist_wheel"
    - stage: deploy
      python: 3.6
      deploy:
        provider: pypi
        user: nklapste
        password:
          secure: UP8MNQxZTpJ/5rsRnpsMLpKuH5dWKypBoNDUvMjKxkCFkVyVmmmudqp0lcE6tNOetrEnDk5N6PIT2j2cTWapZ4gAp56U+m4wrwHBDTp/mUSnPJCtKIVG1qv+0vdUGHpvyHTY1CfP+2dyG6gCoQm9syKOGMD1A3KIgWXNVX9z/KOJwY6UzfzmfgRizjao0yAV2wqYywsJsU8ykS9bt465lD0W27m33SoaAkUnPy2jH56N1Nm7mG7IwB+Mok+6+kSwMnmtAPuABR5F8jGVnY0qhy416x2CXWpkmXpywWWGoAAiu8ala7DOq2z4W8rJNC+AmhygDj3/oGLr8bQckumHvWyWd8GE3IH2F3mi5iYrBGjy/9Puygt+iJqsX2yi5Bv0OxIUMRYLhx4mjS3xt91X+BnmhtORv5JYkcxOeSqy7bIYGgwNx4eYMr0xwZsQ3db6S62CUbrPnse97Sa7WHJL8Z5h1g8TLfPO+jo87zkhTJDwyCq7clkhbnWwJ/dT26I7WpUvpbp7vGOzo6Ee+QtxTHsRTo7st8ShY1URYVQKIL4yG7vfDyPFjPJZpX2PpfrkoWanzvYRIWQpZ0zwC8yCcxIPYgMZdSFhjpuCwdF5qb3H4MyVUb1TuCuzB3Mj1UpqPAa4Axp7b/fUtvEXaLFg3i9SSZQYhH4b6B4kIU8Y/Kw=
        on:
          tags: true
          branch: master
          repo: nklapste/trivector
        distributions: "sdist bdist_wheel"
