language: python
python: 3.6
before_install:
  - pip install codecov
install:
  - pip install .
script:
  - python setup.py test
after_success:
  - codecov
stages:
  - test
  - build
  - deploy
jobs:
  include:
    - stage: test
    - name: "lint"
      script:
        - python setup.py lint || exit $(($? & 35))
    - python: 3.5
    - python: 3.7
      dist: xenial
    - stage: build
      name: "sdist"
      script:
        - python setup.py sdist
    - name: "bdist_wheel"
      install:
        - pip install . wheel
      script:
        - python setup.py bdist_wheel
    - name: "sphinx docs"
      install:
        - pip install .["docs"]
      script:
        - sphinx-build docs/ build/
    - stage: deploy
      deploy:
        provider: pypi
        user: nklapste
        password:
          secure: Rx1M/SfoBIWV8RMjBrsojluQoGk6g99TEk1FsbAsPF3Mr3C8BdaKPLW3VCV44ZmL1UBQg0Okwh+TupOBRBkpyeJtTjxNbnwvJtmKAfjgvYwbw4tYagJZlNU5wOKRNKF/4gMRlzdj4B7/upn8fenUSEK33MomxawV/5/o1c/znB5RUZCyBv55nsN6IVTwpGXv8OWcM2x/6UHMpHqyCQEXvnI+mwxoVkb9TpoTLJoWH+Hr9hmHFuZpmGvXXtn7Z6umM2/KEN5V+Cv4pDUnoFpmF6jlkw/89zX3Bd2e8lVBLwV2TRY59Y4Fi0iK4s0nZLsUVvvLersjwZ7a6c+rtu5q60/AjNr+FHrZifZ0vljrgHrrRSzCYoODBYteLUQLAwR/OXgtrG/3LX8mt9mMLaO5SxF7OmDlvNWabWmKIuuiGsMFB39wRd3NMBJC8e9JmLP+kI3Y+AGAtrmktIUtxvIAhd/JQn5pci325R1DkObhOAxSInvVo53z2xuaNMud2cvNDIzTuzMdBFxAoA67oLHEmfMpVIr8YtXwgBATxQ4GO9uCxT4mbCzUcHIRJhjMFyY15NbyASOeIP85JOCOiU9WjLC/NKdpazapcc6vgfgEvcLbhwA+QupJoyOAQmzTXfC7eOKishj8Oi0rsbtNa6ozEKDKW/SUeBj9PO2NJESzbLQ=
        on:
          tags: true
          branch: master
          repo: nklapste/trivector
        distributions: "sdist bdist_wheel"
