language: python
python: 3.6
before_install:
  - pip install codecov
install:
  - pip install .
script:
  - python setup.py test
after_success:
  - codecov
stages:
  - test
  - build
  - deploy
jobs:
  include:
    - stage: test
    - name: "lint"
      script:
        - python setup.py lint || exit $(($? & 35))
    - python: 3.5
    - python: 3.7
      dist: xenial
    - stage: build
      name: "sdist"
      script:
        - python setup.py sdist
    - name: "bdist_wheel"
      install:
        - pip install . wheel
      script:
        - python setup.py bdist_wheel
    - name: "sphinx docs"
      install:
        - pip install .["docs"]
      script:
        - sphinx-build docs/ build/
    - stage: deploy
      deploy:
        provider: pypi
        user: nklapste
        password:
          secure: h0o5qy0uVEN4RrEK0Got/dRsiT6cq3PAMBNfMpYYXMdwNpb9TBuhWP+Q1ccD7gmn0PIR7zHvvlRIOfN+pdkKfDe0Gb9WD5Na46oHRFQYm90ioB+YSfoEVN+LMaNLmMu/JHSOojDoieclhQBx8FNT48WZHZ0L/unZxSiRaw2VO4oxDF29MaRAxl4wN6w2AgbQDt5dDsYxE/SOsxfFulB7KzOZ/zAMTBf9EoDZ2HKsbhOZUEYiy0VPYVJxERPMIzO1Zqqq5k9IBkIP4jaTEl7zqRkd0/uVn0x6IZ2EvgysizACdeUsPA/txWRhPRGtRBzRLOigy5lzdqb52PXoB7AJxknmdl1LI0IR0wVIfaztogb3CICub8oLkTpYZXdrfRjGBL1bvEN0MqJeYNPy5YCFw1y914Zov3a0p/zlX3NKrBFjSeuqTGCexatDttoI3wuCpCc/M3t0gWWXHfDx2LSFKcq20rCzuiTTeff6UsiTSrmfQevNjtJC9T+2EYhIJcVvlTKcxolwcGkrifcfyYBE4wIGGuE0Ki+fhfMvgqA6wU0tGC17YIP7T7A+fl46I/xpYydXNAnEFla7WBM7fn/F2N35IL/C7Et4S5QWVZVjAypygDAecG76GeGBmagAsl2AALmFxSl2krRBtFiRRkblHfuiat1ucFO1eJQBvlq0dxk=
        on:
          tags: true
          branch: master
          repo: nklapste/trivector
        distributions: "sdist bdist_wheel"
